name: market
description: A new Flutter application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  hawk_fab_menu: ^0.3.2

  http: ^0.12.2
  geolocator: ^5.3.2+2
  shared_preferences: ^0.5.8
  intl: ^0.16.1
  flutter_google_places: ^0.2.6
  google_map_location_picker: ^3.3.3

  path_provider: ^1.6.11
  equatable: ^1.2.3

  url_launcher: ^5.5.0
  contacts_service: ^0.4.6
  clipboard: ^0.1.2+8
  permission_handler: ^5.0.1+1
  
  toast: ^0.1.5
  multi_image_picker: ^4.7.10
  flutter_image_compress: ^0.7.0
  file_picker: ^1.13.2
  
  intl_phone_number_input: ^0.4.6+2
  mobile_number: ^1.0.3
  
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6

  device_id: ^0.2.0
  firebase_messaging: ^6.0.16

  admob_flutter: ^0.3.4

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/flags/
    - assets/logos/
